theme: jekyll-theme-midnight
title: Jacob VanBronkhorst portfolio and random work
description: Initially being forced to start this for extra credit, but eventually will become very useful in my future endeavors 
